<?php
declare(strict_types=1);

// Intercom SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

IntercomUtility::setRegistrar(function (IntercomUtility $u): void {
    $u->clean = [IntercomClean::class, 'call'];
    $u->done = [IntercomDone::class, 'call'];
    $u->make_error = [IntercomMakeError::class, 'call'];
    $u->feature_add = [IntercomFeatureAdd::class, 'call'];
    $u->feature_hook = [IntercomFeatureHook::class, 'call'];
    $u->feature_init = [IntercomFeatureInit::class, 'call'];
    $u->fetcher = [IntercomFetcher::class, 'call'];
    $u->make_fetch_def = [IntercomMakeFetchDef::class, 'call'];
    $u->make_context = [IntercomMakeContext::class, 'call'];
    $u->make_options = [IntercomMakeOptions::class, 'call'];
    $u->make_request = [IntercomMakeRequest::class, 'call'];
    $u->make_response = [IntercomMakeResponse::class, 'call'];
    $u->make_result = [IntercomMakeResult::class, 'call'];
    $u->make_point = [IntercomMakePoint::class, 'call'];
    $u->make_spec = [IntercomMakeSpec::class, 'call'];
    $u->make_url = [IntercomMakeUrl::class, 'call'];
    $u->param = [IntercomParam::class, 'call'];
    $u->prepare_auth = [IntercomPrepareAuth::class, 'call'];
    $u->prepare_body = [IntercomPrepareBody::class, 'call'];
    $u->prepare_headers = [IntercomPrepareHeaders::class, 'call'];
    $u->prepare_method = [IntercomPrepareMethod::class, 'call'];
    $u->prepare_params = [IntercomPrepareParams::class, 'call'];
    $u->prepare_path = [IntercomPreparePath::class, 'call'];
    $u->prepare_query = [IntercomPrepareQuery::class, 'call'];
    $u->graphql_body = [IntercomGraphql::class, 'body'];
    $u->graphql_errors = [IntercomGraphql::class, 'errors'];
    $u->result_basic = [IntercomResultBasic::class, 'call'];
    $u->result_body = [IntercomResultBody::class, 'call'];
    $u->result_headers = [IntercomResultHeaders::class, 'call'];
    $u->transform_request = [IntercomTransformRequest::class, 'call'];
    $u->transform_response = [IntercomTransformResponse::class, 'call'];
});
